/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculadoracliente;

import javax.swing.JDesktopPane;

/**
 *
 * @author asunawesker
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Calculadora
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu = new javax.swing.JMenu();
        jMSuma = new javax.swing.JMenuItem();
        jMResta = new javax.swing.JMenuItem();
        jMMultiplicacion = new javax.swing.JMenuItem();
        jMDivision = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu.setText("Operaciones");

        jMSuma.setText("Suma");
        jMSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMSumaActionPerformed(evt);
            }
        });
        jMenu.add(jMSuma);

        jMResta.setText("Resta");
        jMResta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMRestaActionPerformed(evt);
            }
        });
        jMenu.add(jMResta);

        jMMultiplicacion.setText("Multiplicación");
        jMMultiplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMMultiplicacionActionPerformed(evt);
            }
        });
        jMenu.add(jMMultiplicacion);

        jMDivision.setText("División");
        jMDivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMDivisionActionPerformed(evt);
            }
        });
        jMenu.add(jMDivision);

        jMenuBar1.add(jMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMSumaActionPerformed
        // TODO add your handling code here:
        SumaView sumaview = new SumaView();
        jDesktopPane1.add(sumaview);
        sumaview.setVisible(true);
    }//GEN-LAST:event_jMSumaActionPerformed

    private void jMRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMRestaActionPerformed
        // TODO add your handling code here:
        RestaView restaview = new RestaView();
        jDesktopPane1.add(restaview);
        restaview.setVisible(true);
    }//GEN-LAST:event_jMRestaActionPerformed

    private void jMMultiplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMMultiplicacionActionPerformed
        // TODO add your handling code here:
        MultiplicacionView multiview = new MultiplicacionView();
        jDesktopPane1.add(multiview);
        multiview.setVisible(true);
    }//GEN-LAST:event_jMMultiplicacionActionPerformed

    private void jMDivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMDivisionActionPerformed
        // TODO add your handling code here:
        DivisionView divisionview = new DivisionView();
        jDesktopPane1.add(divisionview);
        divisionview.setVisible(true);
    }//GEN-LAST:event_jMDivisionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenuItem jMDivision;
    private javax.swing.JMenuItem jMMultiplicacion;
    private javax.swing.JMenuItem jMResta;
    private javax.swing.JMenuItem jMSuma;
    private javax.swing.JMenu jMenu;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
